/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const RoomNumber = IDL.Variant({
  'room1' : IDL.Null,
  'room2' : IDL.Null,
});
export const BookingRequestInput = IDL.Record({
  'railwayDivision' : IDL.Text,
  'ppoNumber' : IDL.Text,
  'checkInDate' : Time,
  'guestName' : IDL.Text,
  'roomNumber' : RoomNumber,
  'numGuests' : IDL.Nat,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'checkOutDate' : Time,
  'contactNumber' : IDL.Text,
  'aadhaarNumber' : IDL.Text,
  'pincode' : IDL.Text,
});
export const BookingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const BookingRequestUpdate = IDL.Record({
  'status' : BookingStatus,
  'railwayDivision' : IDL.Text,
  'ppoNumber' : IDL.Text,
  'checkInDate' : Time,
  'guestName' : IDL.Text,
  'roomNumber' : RoomNumber,
  'numGuests' : IDL.Nat,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'checkOutDate' : Time,
  'contactNumber' : IDL.Text,
  'aadhaarNumber' : IDL.Text,
  'pincode' : IDL.Text,
});
export const BookingRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'railwayDivision' : IDL.Text,
  'ppoNumber' : IDL.Text,
  'verifiedMobile' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'checkInDate' : Time,
  'guestName' : IDL.Text,
  'roomNumber' : RoomNumber,
  'numGuests' : IDL.Nat,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'checkOutDate' : Time,
  'contactNumber' : IDL.Text,
  'aadhaarNumber' : IDL.Text,
  'pincode' : IDL.Text,
});
export const AvailabilityInfo = IDL.Record({
  'status' : BookingStatus,
  'checkInDate' : Time,
  'roomNumber' : RoomNumber,
  'checkOutDate' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'approveBooking' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkApproveBookings' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
  'bulkCreateBookings' : IDL.Func(
      [IDL.Vec(BookingRequestInput)],
      [IDL.Vec(IDL.Nat)],
      [],
    ),
  'bulkDeleteBookings' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
  'bulkRejectBookings' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
  'bulkUpdateBookings' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Nat, BookingRequestUpdate))],
      [],
      [],
    ),
  'createBooking' : IDL.Func([BookingRequestInput], [IDL.Opt(IDL.Nat)], []),
  'createOTP' : IDL.Func([IDL.Text], [IDL.Text], []),
  'deleteAllBookings' : IDL.Func([], [], []),
  'deleteBooking' : IDL.Func([IDL.Nat], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [BookingRequest], ['query']),
  'getBookingsByDateRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(AvailabilityInfo)],
      ['query'],
    ),
  'getCallerMobileNumber' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
  'getRoomAvailability' : IDL.Func(
      [RoomNumber],
      [IDL.Vec(AvailabilityInfo)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAuthenticated' : IDL.Func([], [IDL.Bool], ['query']),
  'isMobileAuthenticated' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'rejectBooking' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBooking' : IDL.Func([IDL.Nat, BookingRequestUpdate], [], []),
  'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const RoomNumber = IDL.Variant({ 'room1' : IDL.Null, 'room2' : IDL.Null });
  const BookingRequestInput = IDL.Record({
    'railwayDivision' : IDL.Text,
    'ppoNumber' : IDL.Text,
    'checkInDate' : Time,
    'guestName' : IDL.Text,
    'roomNumber' : RoomNumber,
    'numGuests' : IDL.Nat,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'checkOutDate' : Time,
    'contactNumber' : IDL.Text,
    'aadhaarNumber' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const BookingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const BookingRequestUpdate = IDL.Record({
    'status' : BookingStatus,
    'railwayDivision' : IDL.Text,
    'ppoNumber' : IDL.Text,
    'checkInDate' : Time,
    'guestName' : IDL.Text,
    'roomNumber' : RoomNumber,
    'numGuests' : IDL.Nat,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'checkOutDate' : Time,
    'contactNumber' : IDL.Text,
    'aadhaarNumber' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const BookingRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'railwayDivision' : IDL.Text,
    'ppoNumber' : IDL.Text,
    'verifiedMobile' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'checkInDate' : Time,
    'guestName' : IDL.Text,
    'roomNumber' : RoomNumber,
    'numGuests' : IDL.Nat,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'checkOutDate' : Time,
    'contactNumber' : IDL.Text,
    'aadhaarNumber' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const AvailabilityInfo = IDL.Record({
    'status' : BookingStatus,
    'checkInDate' : Time,
    'roomNumber' : RoomNumber,
    'checkOutDate' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'approveBooking' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkApproveBookings' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
    'bulkCreateBookings' : IDL.Func(
        [IDL.Vec(BookingRequestInput)],
        [IDL.Vec(IDL.Nat)],
        [],
      ),
    'bulkDeleteBookings' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
    'bulkRejectBookings' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
    'bulkUpdateBookings' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Nat, BookingRequestUpdate))],
        [],
        [],
      ),
    'createBooking' : IDL.Func([BookingRequestInput], [IDL.Opt(IDL.Nat)], []),
    'createOTP' : IDL.Func([IDL.Text], [IDL.Text], []),
    'deleteAllBookings' : IDL.Func([], [], []),
    'deleteBooking' : IDL.Func([IDL.Nat], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
    'getBooking' : IDL.Func([IDL.Nat], [BookingRequest], ['query']),
    'getBookingsByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(AvailabilityInfo)],
        ['query'],
      ),
    'getCallerMobileNumber' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
    'getRoomAvailability' : IDL.Func(
        [RoomNumber],
        [IDL.Vec(AvailabilityInfo)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAuthenticated' : IDL.Func([], [IDL.Bool], ['query']),
    'isMobileAuthenticated' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'rejectBooking' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBooking' : IDL.Func([IDL.Nat, BookingRequestUpdate], [], []),
    'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };