/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AvailabilityInfo {
  'status' : BookingStatus,
  'checkInDate' : Time,
  'roomNumber' : RoomNumber,
  'checkOutDate' : Time,
}
export interface BookingRequest {
  'id' : bigint,
  'status' : BookingStatus,
  'railwayDivision' : string,
  'ppoNumber' : string,
  'verifiedMobile' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'checkInDate' : Time,
  'guestName' : string,
  'roomNumber' : RoomNumber,
  'numGuests' : bigint,
  'address' : string,
  'notes' : string,
  'checkOutDate' : Time,
  'contactNumber' : string,
  'aadhaarNumber' : string,
  'pincode' : string,
}
export interface BookingRequestInput {
  'railwayDivision' : string,
  'ppoNumber' : string,
  'checkInDate' : Time,
  'guestName' : string,
  'roomNumber' : RoomNumber,
  'numGuests' : bigint,
  'address' : string,
  'notes' : string,
  'checkOutDate' : Time,
  'contactNumber' : string,
  'aadhaarNumber' : string,
  'pincode' : string,
}
export interface BookingRequestUpdate {
  'status' : BookingStatus,
  'railwayDivision' : string,
  'ppoNumber' : string,
  'checkInDate' : Time,
  'guestName' : string,
  'roomNumber' : RoomNumber,
  'numGuests' : bigint,
  'address' : string,
  'notes' : string,
  'checkOutDate' : Time,
  'contactNumber' : string,
  'aadhaarNumber' : string,
  'pincode' : string,
}
export type BookingStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type RoomNumber = { 'room1' : null } |
  { 'room2' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'approveBooking' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkApproveBookings' : ActorMethod<[Array<bigint>], undefined>,
  'bulkCreateBookings' : ActorMethod<
    [Array<BookingRequestInput>],
    Array<bigint>
  >,
  'bulkDeleteBookings' : ActorMethod<[Array<bigint>], undefined>,
  'bulkRejectBookings' : ActorMethod<[Array<bigint>], undefined>,
  'bulkUpdateBookings' : ActorMethod<
    [Array<[bigint, BookingRequestUpdate]>],
    undefined
  >,
  'createBooking' : ActorMethod<[BookingRequestInput], [] | [bigint]>,
  'createOTP' : ActorMethod<[string], string>,
  'deleteAllBookings' : ActorMethod<[], undefined>,
  'deleteBooking' : ActorMethod<[bigint], undefined>,
  'getAllBookings' : ActorMethod<[], Array<BookingRequest>>,
  'getBooking' : ActorMethod<[bigint], BookingRequest>,
  'getBookingsByDateRange' : ActorMethod<[Time, Time], Array<AvailabilityInfo>>,
  'getCallerMobileNumber' : ActorMethod<[], [] | [string]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyBookings' : ActorMethod<[], Array<BookingRequest>>,
  'getRoomAvailability' : ActorMethod<[RoomNumber], Array<AvailabilityInfo>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerAuthenticated' : ActorMethod<[], boolean>,
  'isMobileAuthenticated' : ActorMethod<[string], boolean>,
  'rejectBooking' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBooking' : ActorMethod<[bigint, BookingRequestUpdate], undefined>,
  'verifyOTP' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];