/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AvailabilityInfo {
    status: BookingStatus;
    checkInDate: Time;
    roomNumber: RoomNumber;
    checkOutDate: Time;
}
export type Time = bigint;
export interface BookingRequestInput {
    railwayDivision: string;
    ppoNumber: string;
    checkInDate: Time;
    guestName: string;
    roomNumber: RoomNumber;
    numGuests: bigint;
    address: string;
    notes: string;
    checkOutDate: Time;
    contactNumber: string;
    aadhaarNumber: string;
    pincode: string;
}
export interface BookingRequestUpdate {
    status: BookingStatus;
    railwayDivision: string;
    ppoNumber: string;
    checkInDate: Time;
    guestName: string;
    roomNumber: RoomNumber;
    numGuests: bigint;
    address: string;
    notes: string;
    checkOutDate: Time;
    contactNumber: string;
    aadhaarNumber: string;
    pincode: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface BookingRequest {
    id: bigint;
    status: BookingStatus;
    railwayDivision: string;
    ppoNumber: string;
    verifiedMobile: string;
    createdAt: Time;
    createdBy: Principal;
    checkInDate: Time;
    guestName: string;
    roomNumber: RoomNumber;
    numGuests: bigint;
    address: string;
    notes: string;
    checkOutDate: Time;
    contactNumber: string;
    aadhaarNumber: string;
    pincode: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum BookingStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum RoomNumber {
    room1 = "room1",
    room2 = "room2"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    approveBooking(id: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkApproveBookings(ids: Array<bigint>): Promise<void>;
    bulkCreateBookings(requests: Array<BookingRequestInput>): Promise<Array<bigint>>;
    bulkDeleteBookings(ids: Array<bigint>): Promise<void>;
    bulkRejectBookings(ids: Array<bigint>): Promise<void>;
    bulkUpdateBookings(updates: Array<[bigint, BookingRequestUpdate]>): Promise<void>;
    createBooking(request: BookingRequestInput): Promise<bigint | null>;
    createOTP(mobileNumber: string): Promise<string>;
    deleteAllBookings(): Promise<void>;
    deleteBooking(id: bigint): Promise<void>;
    getAllBookings(): Promise<Array<BookingRequest>>;
    getBooking(id: bigint): Promise<BookingRequest>;
    getBookingsByDateRange(checkIn: Time, checkOut: Time): Promise<Array<AvailabilityInfo>>;
    getCallerMobileNumber(): Promise<string | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyBookings(): Promise<Array<BookingRequest>>;
    getRoomAvailability(roomNumber: RoomNumber): Promise<Array<AvailabilityInfo>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isCallerAuthenticated(): Promise<boolean>;
    isMobileAuthenticated(mobileNumber: string): Promise<boolean>;
    rejectBooking(id: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBooking(id: bigint, updatedRequest: BookingRequestUpdate): Promise<void>;
    verifyOTP(mobileNumber: string, otp: string): Promise<boolean>;
}
import type { AvailabilityInfo as _AvailabilityInfo, BookingRequest as _BookingRequest, BookingRequestInput as _BookingRequestInput, BookingRequestUpdate as _BookingRequestUpdate, BookingStatus as _BookingStatus, RoomNumber as _RoomNumber, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async approveBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveBooking(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async bulkApproveBookings(arg0: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkApproveBookings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkApproveBookings(arg0);
            return result;
        }
    }
    async bulkCreateBookings(arg0: Array<BookingRequestInput>): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkCreateBookings(to_candid_vec_n10(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkCreateBookings(to_candid_vec_n10(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async bulkDeleteBookings(arg0: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkDeleteBookings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkDeleteBookings(arg0);
            return result;
        }
    }
    async bulkRejectBookings(arg0: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkRejectBookings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkRejectBookings(arg0);
            return result;
        }
    }
    async bulkUpdateBookings(arg0: Array<[bigint, BookingRequestUpdate]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkUpdateBookings(to_candid_vec_n15(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkUpdateBookings(to_candid_vec_n15(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async createBooking(arg0: BookingRequestInput): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(to_candid_BookingRequestInput_n11(this.uploadFile, this.downloadFile, arg0));
                return from_candid_opt_n7(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(to_candid_BookingRequestInput_n11(this.uploadFile, this.downloadFile, arg0));
            return from_candid_opt_n7(this.uploadFile, this.downloadFile, result);
        }
    }
    async createOTP(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createOTP(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOTP(arg0);
            return result;
        }
    }
    async deleteAllBookings(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllBookings();
            return result;
        }
    }
    async deleteBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBooking(arg0);
            return result;
        }
    }
    async getAllBookings(): Promise<Array<BookingRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n21(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n21(this.uploadFile, this.downloadFile, result);
        }
    }
    async getBooking(arg0: bigint): Promise<BookingRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_BookingRequest_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_BookingRequest_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async getBookingsByDateRange(arg0: Time, arg1: Time): Promise<Array<AvailabilityInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByDateRange(arg0, arg1);
                return from_candid_vec_n28(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByDateRange(arg0, arg1);
            return from_candid_vec_n28(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerMobileNumber(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerMobileNumber();
                return from_candid_opt_n31(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerMobileNumber();
            return from_candid_opt_n31(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n32(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n32(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n33(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n33(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMyBookings(): Promise<Array<BookingRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBookings();
                return from_candid_vec_n21(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBookings();
            return from_candid_vec_n21(this.uploadFile, this.downloadFile, result);
        }
    }
    async getRoomAvailability(arg0: RoomNumber): Promise<Array<AvailabilityInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomAvailability(to_candid_RoomNumber_n13(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n28(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomAvailability(to_candid_RoomNumber_n13(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n28(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n32(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n32(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerAuthenticated(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAuthenticated();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAuthenticated();
            return result;
        }
    }
    async isMobileAuthenticated(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isMobileAuthenticated(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isMobileAuthenticated(arg0);
            return result;
        }
    }
    async rejectBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectBooking(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateBooking(arg0: bigint, arg1: BookingRequestUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBooking(arg0, to_candid_BookingRequestUpdate_n17(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBooking(arg0, to_candid_BookingRequestUpdate_n17(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async verifyOTP(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyOTP(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyOTP(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AvailabilityInfo_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AvailabilityInfo): AvailabilityInfo {
    return from_candid_record_n30(uploadFile, downloadFile, value);
}
function from_candid_BookingRequest_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingRequest): BookingRequest {
    return from_candid_record_n23(uploadFile, downloadFile, value);
}
function from_candid_BookingStatus_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n25(uploadFile, downloadFile, value);
}
function from_candid_RoomNumber_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomNumber): RoomNumber {
    return from_candid_variant_n27(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n34(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    railwayDivision: string;
    ppoNumber: string;
    verifiedMobile: string;
    createdAt: _Time;
    createdBy: Principal;
    checkInDate: _Time;
    guestName: string;
    roomNumber: _RoomNumber;
    numGuests: bigint;
    address: string;
    notes: string;
    checkOutDate: _Time;
    contactNumber: string;
    aadhaarNumber: string;
    pincode: string;
}): {
    id: bigint;
    status: BookingStatus;
    railwayDivision: string;
    ppoNumber: string;
    verifiedMobile: string;
    createdAt: Time;
    createdBy: Principal;
    checkInDate: Time;
    guestName: string;
    roomNumber: RoomNumber;
    numGuests: bigint;
    address: string;
    notes: string;
    checkOutDate: Time;
    contactNumber: string;
    aadhaarNumber: string;
    pincode: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n24(uploadFile, downloadFile, value.status),
        railwayDivision: value.railwayDivision,
        ppoNumber: value.ppoNumber,
        verifiedMobile: value.verifiedMobile,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        checkInDate: value.checkInDate,
        guestName: value.guestName,
        roomNumber: from_candid_RoomNumber_n26(uploadFile, downloadFile, value.roomNumber),
        numGuests: value.numGuests,
        address: value.address,
        notes: value.notes,
        checkOutDate: value.checkOutDate,
        contactNumber: value.contactNumber,
        aadhaarNumber: value.aadhaarNumber,
        pincode: value.pincode
    };
}
function from_candid_record_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _BookingStatus;
    checkInDate: _Time;
    roomNumber: _RoomNumber;
    checkOutDate: _Time;
}): {
    status: BookingStatus;
    checkInDate: Time;
    roomNumber: RoomNumber;
    checkOutDate: Time;
} {
    return {
        status: from_candid_BookingStatus_n24(uploadFile, downloadFile, value.status),
        checkInDate: value.checkInDate,
        roomNumber: from_candid_RoomNumber_n26(uploadFile, downloadFile, value.roomNumber),
        checkOutDate: value.checkOutDate
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): BookingStatus {
    return "pending" in value ? BookingStatus.pending : "approved" in value ? BookingStatus.approved : "rejected" in value ? BookingStatus.rejected : value;
}
function from_candid_variant_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    room1: null;
} | {
    room2: null;
}): RoomNumber {
    return "room1" in value ? RoomNumber.room1 : "room2" in value ? RoomNumber.room2 : value;
}
function from_candid_variant_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookingRequest>): Array<BookingRequest> {
    return value.map((x)=>from_candid_BookingRequest_n22(uploadFile, downloadFile, x));
}
function from_candid_vec_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AvailabilityInfo>): Array<AvailabilityInfo> {
    return value.map((x)=>from_candid_AvailabilityInfo_n29(uploadFile, downloadFile, x));
}
function to_candid_BookingRequestInput_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingRequestInput): _BookingRequestInput {
    return to_candid_record_n12(uploadFile, downloadFile, value);
}
function to_candid_BookingRequestUpdate_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingRequestUpdate): _BookingRequestUpdate {
    return to_candid_record_n18(uploadFile, downloadFile, value);
}
function to_candid_BookingStatus_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n20(uploadFile, downloadFile, value);
}
function to_candid_RoomNumber_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomNumber): _RoomNumber {
    return to_candid_variant_n14(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
function to_candid_record_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    railwayDivision: string;
    ppoNumber: string;
    checkInDate: Time;
    guestName: string;
    roomNumber: RoomNumber;
    numGuests: bigint;
    address: string;
    notes: string;
    checkOutDate: Time;
    contactNumber: string;
    aadhaarNumber: string;
    pincode: string;
}): {
    railwayDivision: string;
    ppoNumber: string;
    checkInDate: _Time;
    guestName: string;
    roomNumber: _RoomNumber;
    numGuests: bigint;
    address: string;
    notes: string;
    checkOutDate: _Time;
    contactNumber: string;
    aadhaarNumber: string;
    pincode: string;
} {
    return {
        railwayDivision: value.railwayDivision,
        ppoNumber: value.ppoNumber,
        checkInDate: value.checkInDate,
        guestName: value.guestName,
        roomNumber: to_candid_RoomNumber_n13(uploadFile, downloadFile, value.roomNumber),
        numGuests: value.numGuests,
        address: value.address,
        notes: value.notes,
        checkOutDate: value.checkOutDate,
        contactNumber: value.contactNumber,
        aadhaarNumber: value.aadhaarNumber,
        pincode: value.pincode
    };
}
function to_candid_record_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: BookingStatus;
    railwayDivision: string;
    ppoNumber: string;
    checkInDate: Time;
    guestName: string;
    roomNumber: RoomNumber;
    numGuests: bigint;
    address: string;
    notes: string;
    checkOutDate: Time;
    contactNumber: string;
    aadhaarNumber: string;
    pincode: string;
}): {
    status: _BookingStatus;
    railwayDivision: string;
    ppoNumber: string;
    checkInDate: _Time;
    guestName: string;
    roomNumber: _RoomNumber;
    numGuests: bigint;
    address: string;
    notes: string;
    checkOutDate: _Time;
    contactNumber: string;
    aadhaarNumber: string;
    pincode: string;
} {
    return {
        status: to_candid_BookingStatus_n19(uploadFile, downloadFile, value.status),
        railwayDivision: value.railwayDivision,
        ppoNumber: value.ppoNumber,
        checkInDate: value.checkInDate,
        guestName: value.guestName,
        roomNumber: to_candid_RoomNumber_n13(uploadFile, downloadFile, value.roomNumber),
        numGuests: value.numGuests,
        address: value.address,
        notes: value.notes,
        checkOutDate: value.checkOutDate,
        contactNumber: value.contactNumber,
        aadhaarNumber: value.aadhaarNumber,
        pincode: value.pincode
    };
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_tuple_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, BookingRequestUpdate]): [bigint, _BookingRequestUpdate] {
    return [
        value[0],
        to_candid_BookingRequestUpdate_n17(uploadFile, downloadFile, value[1])
    ];
}
function to_candid_variant_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomNumber): {
    room1: null;
} | {
    room2: null;
} {
    return value == RoomNumber.room1 ? {
        room1: null
    } : value == RoomNumber.room2 ? {
        room2: null
    } : value;
}
function to_candid_variant_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.approved ? {
        approved: null
    } : value == BookingStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<BookingRequestInput>): Array<_BookingRequestInput> {
    return value.map((x)=>to_candid_BookingRequestInput_n11(uploadFile, downloadFile, x));
}
function to_candid_vec_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, BookingRequestUpdate]>): Array<[bigint, _BookingRequestUpdate]> {
    return value.map((x)=>to_candid_tuple_n16(uploadFile, downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
